### ISSUE TITLE
To-do list in script

### ISSUE THREAD

**Issue by BroLeaf** [jyzeng17/quick-neovim-setup#7]
Need use shell script to implement feature below:
- [ ] When startup, store the current path and move to directory of script. Then start working. Return to stored directory after the working is done.
- [ ] If `/.config/nvim_backup` is exist, create new directory with increase number suffix
- [ ] Ask user whether to backup `/.config/nvim_backup` Currently
